language: rust
sudo: false

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

rust:
  - stable
  - beta
  - nightly

script:
  - 'scripts/general/travis.sh build'
  - 'scripts/general/travis.sh test'

deploy:
  provider: script
  script: 'scripts/general/travis.sh deploy'
  on:
    rust: stable
    tags: true
