language: rust
cache: cargo
sudo: false

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script: ./scripts/travis/script.sh

deploy:
  provider: script
  script: ./scripts/travis/deploy.sh
  on:
    rust: stable
    branch: testing/version_check
    tags: true
