language: rust
cache: cargo
sudo: false

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

jobs:
  include:
    - stage: builds
      rust:
        - stable
        - beta
        - nightly
      script: ./scripts/travis.sh build

    - stage: tests
      rust:
        - stable
        - beta
        - nightly
      script: ./scripts/travis.sh test

    - stage: deployments
      rust: stable
      deploy:
        provider: cargo
        token: "${CRATES_TOKEN}"
        on:
          tags: true
