language: rust
cache: cargo
sudo: false

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

jobs:
  include:
    - stage: builds
      rust: stable
      script: './scripts/travis.sh build'
    - rust: beta
      script: './scripts/travis.sh build'
    - rust: nightly
      script: './scripts/travis.sh build'

    - stage: tests
      rust: stable
      script: './scripts/travis.sh test'
    - rust: beta
      script: './scripts/travis.sh test'
    - rust: nightly
      script: './scripts/travis.sh test'

    - stage: deployments
      rust: stable
      before_deploy: cargo doc
      deploy:
        provider: cargo
        token: "${CRATES_TOKEN}"
        on:
          tags: true
