language: rust
cache: cargo
sudo: false

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

- stage: build
  script: ./scripts/travis/build.sh
- stage: test
  script: ./scripts/travis/test.sh

jobs:
  include:
    - stage: deploy
      rust: stable
      deploy:
        provider: cargo
        token: "${CRATES_TOKEN}"
        on:
          branch: testing/version_check
          tags: true
