# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "osmgraphing"
# Changing this version in master and pushing to GitHub
# will lead to publishing it automatically to crates.io.
# Hence do not forget updating Unreleased in CHANGELOG.md.
version = "1.0.0" # !!!
description = "Playing around with graphs created via parsing OpenStreetMap data"
edition = "2018"

authors = [
    "Parga Cacheiro, Dominic (dominic.parga@gmail.com)",
]
repository = "https://github.com/dominicparga/osmgraphing"
readme = "README.md"
keywords = ["osm", "route", "routing", "pbf", "xml"]
categories = ["algorithms", "data-structures", "parser-implementations", "parsing"]
license-file = "LICENSE"


[dependencies]
chrono = "0.4" # pretty date and time
clap = "2.33" # cmdline-parsing
env_logger = "0.6" # logging for external use, e.g. main.rs and examples
log = "0.4"        # logging for internal use, e.g. lib.rs
osmpbfreader = "0.13" # read osm.pbf-files
progressing = "2" # progress-bar

[dev-dependencies]
actix-web = "1" # backend-server
actix-rt = "0.2" # backend-server
futures = "0.1" # backend-server
quick-xml = "0.14" # read xml-files
serde = "1.0" # serialization


[[example]]
name = "parser"
path = "examples/parser.rs"

[[example]]
name = "astar"
path = "examples/astar.rs"

[[example]]
name = "playground_actix"
path = "examples/playground/actix.rs"

[[example]]
name = "edge-containers"
path = "examples/playground/edge_containers.rs"

[[example]]
name = "playground_graph"
path = "examples/playground/graph.rs"

[[example]]
name = "playground_multithreading"
path = "examples/playground/multithreading.rs"

[[example]]
name = "playground_pipes_and_filters"
path = "examples/playground/pipes_and_filters.rs"

[[example]]
name = "playground_xml_reader"
path = "examples/playground/xml_reader.rs"
