[package]
name = "osmgraphing"
version = "0.6.0"
description = "Playing around with graphs created via parsing OpenStreetMap data"
edition = "2018"

authors = [
    "dominicparga <dominic.parga@gmail.com>",
]
repository = "https://github.com/dominicparga/osmgraphing"
readme = "README.md"
keywords = ["osm", "route", "routing", "pbf", "xml"]
categories = ["algorithms", "data-structures", "parser-implementations", "parsing", ""]
license = "Apache-2.0"

[badges]
travis-ci = { repository = "dominicparga/osmgraphing", branch = "master" }


[dependencies]
chrono = "0.4" # pretty date and time
clap = "2.33" # cmdline-parsing
env_logger = "0.6" # logging for external use, e.g. main.rs and examples
log = "0.4"        # logging for internal use, e.g. lib.rs
osmpbfreader = "0.13" # read osm.pbf-files
rand = "0.7" # generate random routes
rand_pcg = "0.2" # generate random routes
serde = "1.0"
csv = "1.1"

[dev-dependencies]
actix-web = "1.0" # backend-server
actix-rt = "0.2" # backend-server
futures = "0.1" # backend-server
quick-xml = "0.14" # read xml-files
serde = "1.0" # serialization


[[example]]
name = "parser"
path = "examples/parser.rs"

[[example]]
name = "astar"
path = "examples/astar.rs"

[[example]]
name = "playground_actix"
path = "examples/playground/actix.rs"

[[example]]
name = "playground_graph"
path = "examples/playground/graph.rs"

[[example]]
name = "playground_multithreading"
path = "examples/playground/multithreading.rs"

[[example]]
name = "playground_pipes_and_filters"
path = "examples/playground/pipes_and_filters.rs"

[[example]]
name = "playground_xml_reader"
path = "examples/playground/xml_reader.rs"
