graph:
  map-file: "resources/maps/small.fmi"
  vehicles:
    type: car
    is-nice-to-use: false
  edges:
    metrics:
    - type: ignore
      id: src-id
    - type: ignore
      id: dst-id
    - type: length
      provided: false
    - type: maxspeed
      provided: true
    - type: duration
      provided: false
    - type: lane-count

routing: # example with two metrics and weights
  metrics: [length, duration]
  preferences:
  - id: length
    alpha: 169
  - id: duration
    alpha: 331
