parser:
  map-file: 'resources/maps/isle-of-man_2020-03-14.ch.fmi'
  vehicles:
    category: 'Car'
    are-drivers-picky: false
  nodes:
  - category: 'NodeId' # node-idx
  - category: 'Ignore' # osm-id
  - category: 'Latitude'
  - category: 'Longitude'
  - category: 'Ignore' # Height
  - category: 'Level'
  edges:
  - category: 'SrcId' # node-idx
  - category: 'DstId' # node-idx
  - category: 'Meters'
  - category: 'KilometersPerHour'
  - category: 'Seconds'
