parser:
  map-file: 'resources/maps/isle-of-man_2020-03-14.fmi'
  vehicles:
    category: 'Car'
    are-drivers-picky: false
  nodes:
  - category: 'NodeId'
  - category: 'Ignore'
  - category: 'Latitude'
  - category: 'Longitude'
  edges:
  - category: 'SrcId'
  - category: 'DstId'
  - category: 'Meters'
  - category: 'KilometersPerHour'
  - category: 'Seconds'
