parser:
  map-file: 'resources/maps/simple-stuttgart.fmi'
  vehicles:
    category: 'Car'
    are-drivers-picky: false
  nodes:
  - category: 'NodeId'
  - category: 'Ignore' # osm-id
  - category: 'Latitude'
  - category: 'Longitude'
  # coming soon:
  # - category: 'Ignore' # height
  # - category: 'Level'
  edges:
  - category: 'SrcId'
    id: 'src-id'
  - category: 'DstId'
    id: 'dst-id'
  - category: 'Meters'
  - category: 'Ignore'
  - category: 'KilometersPerHour'
  - category: 'Seconds'
    is-provided: false
    calc-rules: ['Meters', 'KilometersPerHour']

routing:
- id: 'Meters'
