graph:
  map-file: 'resources/maps/simple-stuttgart.fmi'
  vehicles:
    category: 'Car'
    are-drivers-picky: false
  edges:
  - category: 'NodeId'
    id: 'src-id'
  - category: 'NodeId'
    id: 'dst-id'
  - category: 'Meters'
  - category: 'Ignore'
  - category: 'KilometersPerHour'
  - category: 'Seconds'
    is-provided: false
    calc-rules: ['Meters', 'KilometersPerHour']

routing:
- id: 'Meters'
