parsing:
  map-file: 'resources/maps/small.ch.fmi'
  vehicles:
    category: 'Car'
    are-drivers-picky: false
  nodes:
  - meta: { info: 'NodeId', id: 'node-id' } # node-idx
  - ignored # osm-id
  - metric: { unit: 'Latitude', id: 'latitude' }
  - metric: { unit: 'Longitude', id: 'longitude' }
  - ignored # height
  - meta: { info: 'Level', id: 'level' }
  edges:
  - meta: { info: 'SrcId', id: 'src-id' }
  - meta: { info: 'DstId', id: 'dst-id' }
  - metric: { unit: 'Meters', id: 'meters' }
  - metric: { unit: 'Seconds', id: 'seconds' }
  - meta: { info: 'ShortcutIdx0', id: 'sc-idx-0' }
  - meta: { info: 'ShortcutIdx1', id: 'sc-idx-1' }
  generating:
    nodes: []
    edges:
    - convert:
        from: { unit: 'Meters', id: 'meters' }
        to: { unit: 'Kilometers', id: 'kilometers' }
    - convert:
        from: { unit: 'Seconds', id: 'seconds' }
        to: { unit: 'Minutes', id: 'minutes' }
writing:
  route-pairs:
    file: 'resources/routes/small.ch.fmi.route-pairs'
    random: { seed: 42, count: 100 }
