name: Rust
on:
  push:
  pull_request:
  schedule:
  - cron: '0 6 * * 0-6'
jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup git-token
      uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Test git tagging
      run: |
        git tag -a 'v0.6.1' -m 'See CHANGELOG.md'
        'false'
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build docs
      run: cargo doc
    - name: Deploy and tag
      env:
        CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
      run: |
        cargo publish --token "${CRATES_TOKEN}"
        git tag -a v0.6.1
      continue-on-error: true
  beta:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      run: rustup toolchain install beta
    - run: rustup default beta
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      continue-on-error: true
    - name: Install
      run: rustup toolchain install nightly
      continue-on-error: true
    - run: rustup default nightly
      continue-on-error: true
    - name: Build
      run: cargo build --verbose
      continue-on-error: true
    - name: Run tests
      run: cargo test --verbose
      continue-on-error: true
