name: Rust
on:
  push:
  pull_request:
  schedule:
  - cron: '0 6 * * 0-6'
jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup git-user
      run: |
        git config user.name 'GitHub actions'
        git config user.email 'actions@users.noreply.github.com'
    - name: Test git tagging
      run: |
        echo 'git status'
        git status
        echo 'git tag'
        git tag
        echo 'git config user.name'
        git config user.name
        echo 'git config user.email'
        git config user.email
        echo 'git tag -a "v0.6.1" -m "See CHANGELOG.md"'
        git tag -a "v0.6.1" -m "See CHANGELOG.md"
        echo 'git fetch --all'
        git fetch --all
        echo 'git status'
        git status
        echo 'git tag'
        git tag
        echo 'git config user.name'
        git config user.name
        echo 'git config user.email'
        git config user.email
        echo 'git tag -a "v0.6.1" -m "See CHANGELOG.md"'
        git tag -a "v0.6.1" -m "See CHANGELOG.md"
        'false'
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build docs
      run: cargo doc
    - name: Deploy and tag
      env:
        CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
      run: |
        cargo publish --token "${CRATES_TOKEN}"
        git tag -a "v$(cargo pkgid | cut -d# -f2 | cut -d: -f2)" -m "See CHANGELOG.md"
      continue-on-error: true
  beta:
    runs-on: ubuntu-latest
    steps:
    - run: 'false'
    - uses: actions/checkout@v2
    - name: Install toolchain
      run: rustup toolchain install beta
    - run: rustup default beta
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  nightly:
    runs-on: ubuntu-latest
    steps:
    - run: 'false'
    - uses: actions/checkout@v2
      continue-on-error: true
    - name: Install
      run: rustup toolchain install nightly
      continue-on-error: true
    - run: rustup default nightly
      continue-on-error: true
    - name: Build
      run: cargo build --verbose
      continue-on-error: true
    - name: Run tests
      run: cargo test --verbose
      continue-on-error: true
