name: Rust
on:
  push:
  pull_request:
  schedule:
  - cron: '0 6 * * 0-6'
jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  beta:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: rustup toolchain install beta
      run: rustup default beta
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: rustup toolchain install nightly
      run: rustup default nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
