name: Rust
on:
  push:
  pull_request:
  schedule:
  - cron: '0 6 * * 0-6'
jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build docs
      run: cargo doc
    - name: Deploy
      run: 'false'
    - name: Tag
      if: failure()
      run: echo "Execute 'git tag -a VERSION'"
  beta:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      run: rustup toolchain install beta
    - run: rustup default beta
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      continue-on-error: true
    - name: Install
      run: rustup toolchain install nightly
      continue-on-error: true
    - run: rustup default nightly
      continue-on-error: true
    - name: Build
      run: cargo build --verbose
      continue-on-error: true
    - name: Run tests
      run: cargo test --verbose
      continue-on-error: true
